### ISSUE TITLE
Мужчина, у вас ключ торчит

### ISSUE THREAD

**Issue by wooffie** [Eugenepolyt/-Software-Engineering-2022#14]
https://github.com/Eugenepolyt/-Software-Engineering-2022/blob/fd034100af1b1ea6936721bb8638d1a52070c589/src/main.py#L8

**Comment by Eugenepolyt** [comment]
Аахахахаха

**Comment by Eugenepolyt** [comment]
Думаю мистер преподаватель не захочет создавать свой ключик при проверке
