### ISSUE TITLE
Реализовать приветственное сообщение, удобное меню управление ботом

### ISSUE THREAD

**Issue by Eugenepolyt** [Eugenepolyt/-Software-Engineering-2022#4]
Реализовать понятный интерфейс для пользователя: приветственное сообщение и удобное меню, благодаря которому можно будет управлять ботом

**Comment by SemenMartynov** [comment]
"удобный" -- это функциональное требование?

**Comment by Eugenepolyt** [comment]
> "удобный" -- это функциональное требование?

Изменил, чтобы это было функциональным требованием)
